language: node_js
node_js:
  - "4.1"
before_install:
  - npm set progress=false
  - npm install -g grunt-cli
  - npm install -g phantomjs-prebuilt
  - cp travis_env.json local_env.json
install: npm install
before_script:
  - grunt eslint
  - grunt compile-test
script: npm test
